_format_version: "2.1"
services:
- name: user-details-services
  url: http://host.docker.internal:8080
  routes:
  - name: user-details
    paths:
    - "/user/(?<id>[^/]+)" #regex to map any id number to this route
    strip_path: false